---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y ninja-build libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev
    - name: Build
      run: cargo build --quiet
    - name: Unit tests
      run: cargo test --quiet
    - name: Bytecode interpreter test
      run: |
        cargo run --example test_bc_interpreter examples/example-project.terrificaudio
        cargo run --example test_bc_interpreter manual-tests/manual-tests.terrificaudio
    - name: Cargo clippy
      run: cargo clippy --quiet
    - name: fmt check
      run: cargo fmt --check

